#pragma once
#include "geometry.hpp"
#include "vs_shader.h"
#include "ps_shader.h"
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <d3d11.h>
#include <wrl/client.h>
#include <array>
#include <cstring>
#include <string>
#include <utility>
#include <algorithm>
#pragma comment(lib, "d3d11.lib")

namespace nemesis::preview3d {
template<class T> using com_ptr = Microsoft::WRL::ComPtr<T>;

class renderer {
    com_ptr<ID3D11Device> device_;
    com_ptr<ID3D11DeviceContext> deferred_;
    com_ptr<ID3D11VertexShader> vs_;
    com_ptr<ID3D11PixelShader> ps_;
    com_ptr<ID3D11InputLayout> layout_;
    com_ptr<ID3D11Buffer> vertices_, constants_;
    com_ptr<ID3D11RasterizerState> raster_;
    com_ptr<ID3D11DepthStencilState> depth_state_;
    com_ptr<ID3D11BlendState> blend_state_;
    com_ptr<ID3D11SamplerState> sampler_;
    com_ptr<ID3D11ShaderResourceView> texture_, white_, view_;
    com_ptr<ID3D11Texture2D> target_, depth_;
    com_ptr<ID3D11RenderTargetView> rtv_;
    com_ptr<ID3D11DepthStencilView> dsv_;
    UINT width_{}, height_{}, count_{};
    bool valid_{ false };

    struct constants {
        std::array<float, 4> eye, right, up, forward, projection;
    };
    static_assert(sizeof(constants) == 80);

    bool resize(UINT width, UINT height) {
        if (width == width_ && height == height_ && view_) return true;
        width = std::clamp(width, UINT{16}, UINT{2048});
        height = std::clamp(height, UINT{16}, UINT{2048});

        D3D11_TEXTURE2D_DESC desc{};
        desc.Width = width; desc.Height = height; desc.MipLevels = 1; desc.ArraySize = 1;
        desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM; desc.SampleDesc.Count = 1;
        desc.Usage = D3D11_USAGE_DEFAULT;
        desc.BindFlags = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;

        com_ptr<ID3D11Texture2D> target, depth;
        com_ptr<ID3D11RenderTargetView> rtv;
        com_ptr<ID3D11ShaderResourceView> view;
        com_ptr<ID3D11DepthStencilView> dsv;

        if (FAILED(device_->CreateTexture2D(&desc, nullptr, target.GetAddressOf()))) return false;
        if (FAILED(device_->CreateRenderTargetView(target.Get(), nullptr, rtv.GetAddressOf()))) return false;
        if (FAILED(device_->CreateShaderResourceView(target.Get(), nullptr, view.GetAddressOf()))) return false;

        desc.Format = DXGI_FORMAT_D24_UNORM_S8_UINT;
        desc.BindFlags = D3D11_BIND_DEPTH_STENCIL;
        if (FAILED(device_->CreateTexture2D(&desc, nullptr, depth.GetAddressOf()))) return false;
        if (FAILED(device_->CreateDepthStencilView(depth.Get(), nullptr, dsv.GetAddressOf()))) return false;

        target_ = std::move(target); depth_ = std::move(depth); rtv_ = std::move(rtv);
        view_ = std::move(view); dsv_ = std::move(dsv); width_ = width; height_ = height;
        return true;
    }

public:
    explicit renderer(ID3D11Device* device) : device_(device) {
        if (!device) return;

        // Create deferred context for clean, isolated state recording
        device->CreateDeferredContext(0, deferred_.GetAddressOf());

        // Create shaders from pre-compiled bytecode (generated by fxc.exe)
        if (FAILED(device->CreateVertexShader(g_vs_shader, sizeof(g_vs_shader), nullptr, vs_.GetAddressOf()))) return;
        if (FAILED(device->CreatePixelShader(g_ps_shader, sizeof(g_ps_shader), nullptr, ps_.GetAddressOf()))) return;

        const D3D11_INPUT_ELEMENT_DESC elements[] = {
            {"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT,    0,  0, D3D11_INPUT_PER_VERTEX_DATA, 0},
            {"NORMAL",   0, DXGI_FORMAT_R32G32B32_FLOAT,    0, 12, D3D11_INPUT_PER_VERTEX_DATA, 0},
            {"TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT,       0, 24, D3D11_INPUT_PER_VERTEX_DATA, 0},
            {"COLOR",    0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, 32, D3D11_INPUT_PER_VERTEX_DATA, 0}
        };
        if (FAILED(device->CreateInputLayout(elements, 4, g_vs_shader, sizeof(g_vs_shader), layout_.GetAddressOf()))) return;

        D3D11_BUFFER_DESC cb{};
        cb.ByteWidth = sizeof(constants);
        cb.Usage = D3D11_USAGE_DYNAMIC;
        cb.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
        cb.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
        if (FAILED(device->CreateBuffer(&cb, nullptr, constants_.GetAddressOf()))) return;

        D3D11_RASTERIZER_DESC rs{};
        rs.FillMode = D3D11_FILL_SOLID;
        rs.CullMode = D3D11_CULL_NONE;
        rs.DepthClipEnable = TRUE;
        if (FAILED(device->CreateRasterizerState(&rs, raster_.GetAddressOf()))) return;

        D3D11_DEPTH_STENCIL_DESC ds{};
        ds.DepthEnable = TRUE;
        ds.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ALL;
        ds.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
        if (FAILED(device->CreateDepthStencilState(&ds, depth_state_.GetAddressOf()))) return;

        D3D11_BLEND_DESC bd{};
        bd.RenderTarget[0].BlendEnable = TRUE;
        bd.RenderTarget[0].SrcBlend = D3D11_BLEND_SRC_ALPHA;
        bd.RenderTarget[0].DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
        bd.RenderTarget[0].BlendOp = D3D11_BLEND_OP_ADD;
        bd.RenderTarget[0].SrcBlendAlpha = D3D11_BLEND_ONE;
        bd.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;
        bd.RenderTarget[0].BlendOpAlpha = D3D11_BLEND_OP_ADD;
        bd.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
        if (FAILED(device->CreateBlendState(&bd, blend_state_.GetAddressOf()))) return;

        D3D11_SAMPLER_DESC ss{};
        ss.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
        ss.AddressU = ss.AddressV = ss.AddressW = D3D11_TEXTURE_ADDRESS_WRAP;
        ss.ComparisonFunc = D3D11_COMPARISON_ALWAYS;
        ss.MaxLOD = D3D11_FLOAT32_MAX;
        if (FAILED(device->CreateSamplerState(&ss, sampler_.GetAddressOf()))) return;

        D3D11_TEXTURE2D_DESC td{};
        td.Width = td.Height = td.MipLevels = td.ArraySize = 1;
        td.SampleDesc.Count = 1;
        td.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
        td.Usage = D3D11_USAGE_IMMUTABLE;
        td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
        const std::uint32_t pixel = 0xffffffffu;
        const D3D11_SUBRESOURCE_DATA init{&pixel, 4, 0};
        com_ptr<ID3D11Texture2D> tex;
        if (FAILED(device->CreateTexture2D(&td, &init, tex.GetAddressOf()))) return;
        if (FAILED(device->CreateShaderResourceView(tex.Get(), nullptr, white_.GetAddressOf()))) return;

        valid_ = true;
    }

    bool is_valid() const { return valid_ && device_ != nullptr; }

    bool upload(const mesh& m, ID3D11ShaderResourceView* texture = nullptr) {
        if (!valid_ || m.vertices.empty()) return false;
        D3D11_BUFFER_DESC desc{};
        desc.ByteWidth = static_cast<UINT>(m.vertices.size() * sizeof(vertex));
        desc.Usage = D3D11_USAGE_IMMUTABLE;
        desc.BindFlags = D3D11_BIND_VERTEX_BUFFER;
        const D3D11_SUBRESOURCE_DATA init{m.vertices.data(), 0, 0};
        com_ptr<ID3D11Buffer> buffer;
        if (FAILED(device_->CreateBuffer(&desc, &init, buffer.GetAddressOf()))) return false;
        vertices_ = std::move(buffer);
        count_ = static_cast<UINT>(m.vertices.size());
        texture_ = texture;
        return true;
    }

    ID3D11Device* device() const { return device_.Get(); }

    ID3D11ShaderResourceView* render(const camera& cam, UINT width, UINT height) {
        if (!valid_ || !vertices_ || count_ == 0) return nullptr;
        if (!resize(width, height)) return nullptr;

        const auto e = cam.eye(), r = cam.right(), u = cam.up(), f = cam.forward();
        constexpr float near_z = 0.02f, far_z = 100.0f;
        const constants data{
            {e.x, e.y, e.z, 0},
            {r.x, r.y, r.z, 0},
            {u.x, u.y, u.z, 0},
            {f.x, f.y, f.z, 0},
            {1.0f / (camera::tangent * static_cast<float>(width_) / height_),
             1.0f / camera::tangent,
             far_z / (far_z - near_z),
             -near_z * far_z / (far_z - near_z)}
        };

        if (deferred_) {
            // Primary path: Use deferred context + ExecuteCommandList(commands, RestoreContextState=TRUE)
            // This guarantees 100% hardware-managed pipeline preservation for CS2 and xdraw
            deferred_->ClearState();

            D3D11_MAPPED_SUBRESOURCE mapped{};
            if (FAILED(deferred_->Map(constants_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) return nullptr;
            std::memcpy(mapped.pData, &data, sizeof(data));
            deferred_->Unmap(constants_.Get(), 0);

            ID3D11RenderTargetView* rtv = rtv_.Get();
            deferred_->OMSetRenderTargets(1, &rtv, dsv_.Get());
            const float clear[] = {0.0f, 0.0f, 0.0f, 0.0f};
            deferred_->ClearRenderTargetView(rtv, clear);
            deferred_->ClearDepthStencilView(dsv_.Get(), D3D11_CLEAR_DEPTH | D3D11_CLEAR_STENCIL, 1.0f, 0);

            const D3D11_VIEWPORT vp{0.0f, 0.0f, static_cast<float>(width_), static_cast<float>(height_), 0.0f, 1.0f};
            deferred_->RSSetViewports(1, &vp);
            deferred_->RSSetState(raster_.Get());
            deferred_->OMSetDepthStencilState(depth_state_.Get(), 0);
            deferred_->OMSetBlendState(blend_state_.Get(), nullptr, 0xffffffffu);
            deferred_->IASetInputLayout(layout_.Get());
            deferred_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

            const UINT stride = sizeof(vertex), offset = 0;
            ID3D11Buffer* vb = vertices_.Get();
            ID3D11Buffer* cb = constants_.Get();
            deferred_->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
            deferred_->VSSetShader(vs_.Get(), nullptr, 0);
            deferred_->VSSetConstantBuffers(0, 1, &cb);
            deferred_->PSSetShader(ps_.Get(), nullptr, 0);

            ID3D11ShaderResourceView* srv = texture_ ? texture_.Get() : white_.Get();
            ID3D11SamplerState* sample = sampler_.Get();
            deferred_->PSSetShaderResources(0, 1, &srv);
            deferred_->PSSetSamplers(0, 1, &sample);
            deferred_->Draw(count_, 0);

            com_ptr<ID3D11CommandList> commands;
            if (SUCCEEDED(deferred_->FinishCommandList(FALSE, commands.GetAddressOf()))) {
                com_ptr<ID3D11DeviceContext> immediate;
                device_->GetImmediateContext(immediate.GetAddressOf());
                if (immediate) {
                    immediate->ExecuteCommandList(commands.Get(), TRUE); // TRUE = RestoreContextState
                }
            }
            return view_.Get();
        }

        // Fallback path: Immediate context with full state save and restore
        com_ptr<ID3D11DeviceContext> ctx;
        device_->GetImmediateContext(ctx.GetAddressOf());
        if (!ctx) return nullptr;

        com_ptr<ID3D11RenderTargetView> old_rtv;
        com_ptr<ID3D11DepthStencilView> old_dsv;
        ctx->OMGetRenderTargets(1, old_rtv.GetAddressOf(), old_dsv.GetAddressOf());
        D3D11_VIEWPORT old_vp{}; UINT vp_count = 1;
        ctx->RSGetViewports(&vp_count, &old_vp);
        com_ptr<ID3D11RasterizerState> old_rs; ctx->RSGetState(old_rs.GetAddressOf());
        com_ptr<ID3D11DepthStencilState> old_dss; UINT old_stencil_ref = 0;
        ctx->OMGetDepthStencilState(old_dss.GetAddressOf(), &old_stencil_ref);
        com_ptr<ID3D11BlendState> old_bs; float old_blend_factor[4] = {}; UINT old_sample_mask = 0xffffffff;
        ctx->OMGetBlendState(old_bs.GetAddressOf(), old_blend_factor, &old_sample_mask);
        com_ptr<ID3D11InputLayout> old_layout; ctx->IAGetInputLayout(old_layout.GetAddressOf());
        D3D11_PRIMITIVE_TOPOLOGY old_topology = D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED;
        ctx->IAGetPrimitiveTopology(&old_topology);
        com_ptr<ID3D11VertexShader> old_vs; ctx->VSGetShader(old_vs.GetAddressOf(), nullptr, nullptr);
        com_ptr<ID3D11PixelShader> old_ps; ctx->PSGetShader(old_ps.GetAddressOf(), nullptr, nullptr);
        com_ptr<ID3D11Buffer> old_vb; UINT old_stride = 0, old_offset = 0;
        ctx->IAGetVertexBuffers(0, 1, old_vb.GetAddressOf(), &old_stride, &old_offset);
        com_ptr<ID3D11Buffer> old_cb_vs; ctx->VSGetConstantBuffers(0, 1, old_cb_vs.GetAddressOf());
        com_ptr<ID3D11ShaderResourceView> old_ps_srv; ctx->PSGetShaderResources(0, 1, old_ps_srv.GetAddressOf());
        com_ptr<ID3D11SamplerState> old_ps_sampler; ctx->PSGetSamplers(0, 1, old_ps_sampler.GetAddressOf());

        D3D11_MAPPED_SUBRESOURCE mapped{};
        if (FAILED(ctx->Map(constants_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) return nullptr;
        std::memcpy(mapped.pData, &data, sizeof(data));
        ctx->Unmap(constants_.Get(), 0);

        ID3D11RenderTargetView* rtv = rtv_.Get();
        ctx->OMSetRenderTargets(1, &rtv, dsv_.Get());
        const float clear[] = {0.0f, 0.0f, 0.0f, 0.0f};
        ctx->ClearRenderTargetView(rtv, clear);
        ctx->ClearDepthStencilView(dsv_.Get(), D3D11_CLEAR_DEPTH | D3D11_CLEAR_STENCIL, 1.0f, 0);

        const D3D11_VIEWPORT vp{0.0f, 0.0f, static_cast<float>(width_), static_cast<float>(height_), 0.0f, 1.0f};
        ctx->RSSetViewports(1, &vp);
        ctx->RSSetState(raster_.Get());
        ctx->OMSetDepthStencilState(depth_state_.Get(), 0);
        ctx->OMSetBlendState(blend_state_.Get(), nullptr, 0xffffffffu);
        ctx->IASetInputLayout(layout_.Get());
        ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

        const UINT stride = sizeof(vertex), offset = 0;
        ID3D11Buffer* vb = vertices_.Get();
        ID3D11Buffer* cb = constants_.Get();
        ctx->IASetVertexBuffers(0, 1, &vb, &stride, &offset);
        ctx->VSSetShader(vs_.Get(), nullptr, 0);
        ctx->VSSetConstantBuffers(0, 1, &cb);
        ctx->PSSetShader(ps_.Get(), nullptr, 0);

        ID3D11ShaderResourceView* srv = texture_ ? texture_.Get() : white_.Get();
        ID3D11SamplerState* sample = sampler_.Get();
        ctx->PSSetShaderResources(0, 1, &srv);
        ctx->PSSetSamplers(0, 1, &sample);
        ctx->Draw(count_, 0);

        // Restore state
        ID3D11RenderTargetView* old_rtv_raw = old_rtv.Get();
        ctx->OMSetRenderTargets(1, &old_rtv_raw, old_dsv.Get());
        if (vp_count > 0) ctx->RSSetViewports(1, &old_vp);
        ctx->RSSetState(old_rs.Get());
        ctx->OMSetDepthStencilState(old_dss.Get(), old_stencil_ref);
        ctx->OMSetBlendState(old_bs.Get(), old_blend_factor, old_sample_mask);
        ctx->IASetInputLayout(old_layout.Get());
        ctx->IASetPrimitiveTopology(old_topology);
        ctx->VSSetShader(old_vs.Get(), nullptr, 0);
        ctx->PSSetShader(old_ps.Get(), nullptr, 0);
        ID3D11Buffer* old_vb_raw = old_vb.Get();
        ctx->IASetVertexBuffers(0, 1, &old_vb_raw, &old_stride, &old_offset);
        ID3D11Buffer* old_cb_vs_raw = old_cb_vs.Get();
        ctx->VSSetConstantBuffers(0, 1, &old_cb_vs_raw);
        ID3D11ShaderResourceView* old_ps_srv_raw = old_ps_srv.Get();
        ctx->PSSetShaderResources(0, 1, &old_ps_srv_raw);
        ID3D11SamplerState* old_ps_sampler_raw = old_ps_sampler.Get();
        ctx->PSSetSamplers(0, 1, &old_ps_sampler_raw);

        return view_.Get();
    }
};
} // namespace nemesis::preview3d
