p = r'C:\Users\stass\OneDrive\Documents\OneTap\gaycity\mintaly-cs2\project\core\hooks\impl\cheat.cpp'
d = open(p, 'rb').read()

old = b'HRESULT __fastcall cheat::present( IDXGISwapChain* thisptr, UINT sync_interval, UINT flags )\r\n\t{\r\n\t\tdiag::exception_scope scope{ "present" };\r\n\t\tif ( lifecycle::is_unloading( ) )\r\n\t\t{\r\n\t\t\treturn m_present.call<HRESULT>( thisptr, sync_interval, flags );\r\n\t\t}\r\n\r\n\t\t// A NULL or corrupt swap-chain pointer dereferences [thisptr+0x10] inside\r\n\t\t// the original Present and faults. Fail closed instead of crashing the game.\r\n\t\tif ( !thisptr )\r\n\t\t\treturn E_FAIL;\r\n\t\t// safe_read runs its own SEH frame, so no __try here (MSVC C2712).\r\n\t\t// Reads the vtable pointer stored at the swap-chain address.\r\n\t\tif ( !memory::safe_read<std::uintptr_t>( reinterpret_cast<std::uintptr_t>( thisptr ) ).value_or( 0 ) )\r\n\t\t\treturn E_FAIL;\r\n\r\n\t\tstatic auto last_sub_check = std::chrono::steady_clock::now( );'

new = b'HRESULT __fastcall cheat::present( IDXGISwapChain* thisptr, UINT sync_interval, UINT flags )\r\n\t{\r\n\t\t// Top-level SEH: the engine' + b'\'s' + b' Present can fault on a stale/destroyed swap\r\n\t\t// chain during level transitions. Catch it here to avoid process crash.\r\n\t\t__try\r\n\t\t{\r\n\t\t\tdiag::exception_scope scope{ "present" };\r\n\t\t\tif ( lifecycle::is_unloading( ) )\r\n\t\t\t{\r\n\t\t\t\treturn m_present.call<HRESULT>( thisptr, sync_interval, flags );\r\n\t\t\t}\r\n\r\n\t\t\t// A NULL or corrupt swap-chain pointer dereferences [thisptr+0x10] inside\r\n\t\t\t// the original Present and faults. Fail closed instead of crashing the game.\r\n\t\t\tif ( !thisptr )\r\n\t\t\t\treturn E_FAIL;\r\n\t\t\t// safe_read runs its own SEH frame, so no __try here (MSVC C2712).\r\n\t\t\t// Reads the vtable pointer stored at the swap-chain address.\r\n\t\t\tif ( !memory::safe_read<std::uintptr_t>( reinterpret_cast<std::uintptr_t>( thisptr ) ).value_or( 0 ) )\r\n\t\t\t\treturn E_FAIL;\r\n\r\n\t\t\t// Additional validation: check if the swap chain' + b'\'s' + b' device pointer is valid.\r\n\t\t\t// A destroyed swap chain during level transition may have a valid vtable\r\n\t\t\t// but a NULL device pointer, causing the engine' + b'\'s' + b' Present to crash.\r\n\t\t\tIDXGISwapChain* swap_chain = thisptr;\r\n\t\t\tID3D11Device* device = nullptr;\r\n\t\t\t__try\r\n\t\t\t{\r\n\t\t\t\tif ( FAILED( swap_chain->GetDevice( __uuidof( ID3D11Device ), reinterpret_cast< void** >( &device ) ) ) || !device )\r\n\t\t\t\t\treturn E_FAIL;\r\n\t\t\t\tdevice->Release( );\r\n\t\t\t}\r\n\t\t\t__except ( EXCEPTION_EXECUTE_HANDLER )\r\n\t\t\t{\r\n\t\t\t\treturn E_FAIL;\r\n\t\t\t}\r\n\r\n\t\t\tstatic auto last_sub_check = std::chrono::steady_clock::now( );'

n = d.count(old)
print('occurrences', n)
assert n == 1
d = d.replace(old, new)
open(p, 'wb').write(d)
print('written', len(d))